[package]
name = "viewer"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pollster = "0.3.0"
rive-rs = { path = "../../rive-rs", features = ["vello"] }
vello = "0.1.0"
wgpu = "0.19.3"
winit = "0.29.13"
